# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat_loss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancyhours',
            name='occupancy',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='soiltemp',
            name='reference',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='weather',
            name='reference',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='engineeringvariables',
            name='variables',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='heatlossscenarios',
            name='scenarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='radiators',
            name='reference',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
